
server:
  # port: ${PORT:8080}
  servlet:
    context-path: "/api/v1"

spring:
  datasource:
    url: jdbc:h2:mem:todo
    driverClassName: "org.h2.Driver"
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2db